name: aegnn
channels:
  - pyg
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - click=8.0.4
  - intel-openmp=2021.4.0
  - yaml=0.2.5
  - expat=2.4.4
  - lz4-c=1.9.3
  - zstd=1.4.9
  - giflib=5.2.1
  - mkl_random=1.2.2
  - freetype=2.11.0
  - libgcc-ng=9.3.0
  - kiwisolver=1.3.2
  - gitpython=3.1.18
  - libxml2=2.9.12
  - ffmpeg=4.3
  - setproctitle=1.2.2
  - six=1.16.0
  - typing-extensions=4.1.1
  - icu=58.2
  - numpy-base=1.21.5
  - pycparser=2.21
  - pyyaml=6.0
  - tk=8.6.11
  - setuptools=61.2.0
  - blas==1.0=mkl
  - networkx=2.7.1
  - brotli=1.0.9
  - python=3.8.13
  - libiconv=1.16
  - libxcb=1.14
  - bottleneck=1.3.4
  - openssl
  - joblib=1.1.0
  - fontconfig=2.13.1
  - psutil=5.8.0
  - wandb=0.12.15
  - pyparsing=3.0.4
  - gst-plugins-base=1.14.0
  - idna=3.3
  - cycler=0.11.0
  - mkl-service=2.4.0
  - pytorch-spline-conv=1.2.1
  - certifi
  - smmap=4.0.0
  - pillow=9.0.1
  - xz=5.2.5
  - ld_impl_linux-64=2.35.1
  - libgomp=9.3.0
  - matplotlib-base=3.5.1
  - nettle=3.7.3
  - pyopenssl=22.0.0
  - dbus=1.13.18
  - numexpr=2.8.1
  - libtasn1=4.16.0
  - yacs=0.1.6
  - libidn2=2.3.2
  - requests=2.27.1
  - tqdm=4.64.0
  - pathtools=0.1.2
  - python_abi=3.8
  - brotlipy=0.7.0
  - mkl=2021.4.0
  - _libgcc_mutex==0.1=main
  - libpng=1.6.37
  - urllib3=1.26.9
  - threadpoolctl=2.2.0
  - lame=3.100
  - pyqt=5.9.2
  - pytorch-sparse=0.6.13
  - _openmp_mutex==4.5=1_gnu
  - libprotobuf=3.19.1
  - pip=21.2.4
  - libuuid=1.0.3
  - torchvision=0.12.0
  - pytorch-mutex==1.0=cuda
  - pandas=1.4.2
  - ca-certificates
  - qt=5.9.7
  - matplotlib=3.5.1
  - sip=4.19.13
  - numpy=1.21.5
  - bzip2=1.0.8
  - munkres=1.1.4
  - fonttools=4.25.0
  - tornado=6.1
  - libtiff=4.2.0
  - mkl_fft=1.3.1
  - cryptography=36.0.0
  - gnutls=3.6.15
  - pcre=8.45
  - sqlite=3.38.3
  - pytorch==1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - protobuf=3.19.1
  - scikit-learn=1.0.2
  - libstdcxx-ng=9.3.0
  - docker-pycreds=0.4.0
  - python-dateutil=2.8.2
  - libgfortran4=7.5.0
  - cffi=1.15.0
  - pytorch-scatter=2.0.9
  - pytorch-cluster=1.6.0
  - lcms2=2.12
  - pytz=2021.3
  - openh264=2.1.1
  - promise=2.3
  - gstreamer=1.14.0
  - readline=8.1.2
  - wheel=0.37.1
  - libgfortran-ng=7.5.0
  - libwebp-base=1.2.2
  - typing_extensions=4.1.1
  - sentry-sdk=1.5.11
  - torchaudio=0.11.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - gmp=6.2.1
  - markupsafe=2.0.1
  - jinja2=3.0.3
  - charset-normalizer=2.0.4
  - pysocks=1.7.1
  - packaging=21.3
  - python-louvain=0.15
  - jpeg=9e
  - zlib=1.2.12
  - shortuuid=1.0.8
  - ncurses=6.3
  - libffi=3.3
  - glib=2.69.1
  - gitdb=4.0.7
  - scipy=1.7.3
  - libuv=1.40.0
  - pyg=2.0.4
  - multiprocess
  - nbformat
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.0.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - grpcio==1.46.0
    - importlib-metadata==4.11.3
    - mapcalc==0.2.2
    - markdown==3.3.7
    - multidict==6.0.2
    - oauthlib==3.2.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pytorch-lightning==1.4.9
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torchmetrics==0.4.0
    - werkzeug==2.1.2
    - yarl==1.7.2
    - zipp==3.8.0
    - ipython
    - open3d
